@baseurl = http://localhost:3000
### Get All DactyText 

GET {{baseurl}}/texts

### Get one dactyText

GET {{baseurl}}/texts/e4e9b7a1-8d0f-4c12-9c4b-7f3e8a5a1f2b

### Create one DactyText
POST {{baseurl}}/texts
Content-Type: application/json

{
    "content" : "Hello",
    "level": "medium"
}

### Create one DactyText ( should fail )
POST {{baseurl}}/texts
Content-Type: application/json

{
    "content" : "Hello",
    "level": "Test "
}

### Delete a text
DELETE {{baseurl}}/texts/e4e9b7a1-8d0f-4c12-9c4b-7f3e8a5a1f2b
